App\DTO\Flight:
    properties:
        countryCode:
            - NotBlank: ~
            - Country: ~
        status:
            - notBlank: ~
        detail:
            - notBlank: ~
            - Type: integer